### ISSUE TITLE
JuliaCon Meetup

### ISSUE THREAD

**Issue by jpfairbanks** [inguar/Junet.jl#1]
Hi @inguar,

I found this repo based on your upcoming talk at JuliaCon. @sbromberger and I would like to meet up with you at the conference in two weeks. It looks like we are both speaking on Wed afternoon.

James

**Comment by inguar** [comment]
Hi James, great idea. I think we could meet up before the session and possibly coordinate our talks. It would also be really interesting to talk about building network analysis tools for Julia. See you in 2 weeks in Berkeley!

-- Igor

**Comment by jpfairbanks** [comment]
It was nice to meet you today. Lets meet up more after our talks!

**Comment by inguar** [comment]
Sure! Nice meeting you too.
