### ISSUE TITLE
install package Junet.jl

### ISSUE THREAD

**Issue by liwen-alt** [inguar/Junet.jl#9]
I've tried a lot of ways. I always failed to install junet. Can you help me? How can I install junet correctly.
![image](https://user-images.githubusercontent.com/63285313/83939636-0b8e3180-a811-11ea-919a-f5ad29fa927d.png)
![image](https://user-images.githubusercontent.com/63285313/83939738-d8986d80-a811-11ea-80d5-1e441b2cc291.png)

**Comment by inguar** [comment]
Sorry for a slow reply. I am no longer actively working on this project. Try running the following in package mode; it seems to have worked for me just now:
`add "git://github.com/inguar/Junet.jl.git"`

Speaking of the library choice, you should try [LightGraphs](https://github.com/JuliaGraphs/LightGraphs.jl). AFAIK, it is still actively maintained and they have reproduced my performance tricks, so the speeds should be similar.
